version: '3'
services:
  openldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "hmnd"
      LDAP_DOMAIN: "hmnd.de"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD}"
      LDAP_TLS_VERIFY_CLIENT: "try"
    ports:
      - "389:389"
    volumes:
      - /data/ldap-hmnd-de/database:/var/lib/ldap
      - /data/ldap-hmnd-de/config:/etc/ldap/slapd.d

  admin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    networks:
    - default
    - traefik_net
    labels:
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:ldap.hmnd.de"
    - "traefik.docker.network=traefik_net"

networks:
  traefik_net:
    external: true